import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './style.css'
import Aside from '@/components/Aside'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='layout-grid'>
                    <nav className='py-8'>
                        <Header/>
                    </nav>
                    <aside className='aside '>
                        <Aside/>
                    </aside>
                    <main className='main overflow-y-auto p-4 bg-white'>
                        {children}
                    </main>
                </div>
            </body>
        </html>
    )
}
